### ISSUE TITLE
why this comparison with no effect ?

### ISSUE THREAD

**Issue by vurte** [henrik/rails#1]
https://github.com/henrik/rails/blob/326d77fe473a39086d7e3597a379aa50bfcae0bc/activerecord/lib/active_record/persistence.rb#L227

**Comment by vurte** [comment]
It is not returned or used in a statement.

**Comment by henrik** [comment]
Seems this code was moved from the end of the method where it would affect the return value: https://github.com/henrik/rails/commit/326d77fe473a39086d7e3597a379aa50bfcae0bc

So looks it was a mistake.

This is just an old, unused fork of rails, though :) You could check if the same code is in Rails proper (I suspect not).
